defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
  ['README.md', 'Gemfile.lock', 'Gemfile', 'non-published']
